/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ThemeLazyImport = createFileRoute('/theme')()
const BoardsLazyImport = createFileRoute('/boards')()
const IndexLazyImport = createFileRoute('/')()
const BoardBoardIdLazyImport = createFileRoute('/board/$boardId')()

// Create/Update Routes

const ThemeLazyRoute = ThemeLazyImport.update({
  path: '/theme',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/theme.lazy').then((d) => d.Route))

const BoardsLazyRoute = BoardsLazyImport.update({
  path: '/boards',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/boards.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BoardBoardIdLazyRoute = BoardBoardIdLazyImport.update({
  path: '/board/$boardId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/board/$boardId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsLazyImport
      parentRoute: typeof rootRoute
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeLazyImport
      parentRoute: typeof rootRoute
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BoardsLazyRoute,
  ThemeLazyRoute,
  BoardBoardIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/boards",
        "/theme",
        "/board/$boardId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/boards": {
      "filePath": "boards.lazy.tsx"
    },
    "/theme": {
      "filePath": "theme.lazy.tsx"
    },
    "/board/$boardId": {
      "filePath": "board/$boardId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
